---
- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  become: true

- name: Restart libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
  become: true